import "@/styles/global.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Vibe Json Formatter",
  description: "Json formatter generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
